// Simulated premise recording — the synthetic stand-in for Tab 0's ROI 1 figure.
//
// WHY THIS EXISTS. The premise figure argues that spikes and calcium correspond only
// SOMETIMES. Making that argument well wants a zoomable plot, and a zoomable plot needs
// per-sample data — which, for the real recording, means publishing an unpublished
// recording from a public URL. This model reproduces the phenomenon instead, so the
// figure can be as interactive as it likes at zero disclosure cost (CLAUDE.md repo
// hygiene; the real-data episode is recorded in docs/img/README.txt).
//
// THE MODEL, in one line:
//
//     calcium(t) = Σ AP-linked events  +  Σ AP-independent events  +  measurement noise
//
// AP-linked events fall out of convolution rather than being placed: action potentials
// arrive in CLUSTERS of 1–5, and because convolution is linear a 5-AP cluster produces a
// transient roughly five times a single-AP one, with no special-casing. That IS the
// hypothesis the tool exists to test — every calcium event is the same kernel stamped
// down once per spike — so the simulation is the null model, generated by the same
// primitives Tab 1 uses to teach it.
//
// AP-independent events are the violation: kernel-shaped transients with NO spike beneath
// them. Three of them, matching what the real recording shows. They also decay more slowly
// than the AP-linked events, as the real one does — which is itself a clue that they are
// not the same process, and is exactly the kind of thing the kernel diagnostics surface.
//
// Everything is seeded, so the figure is byte-stable across regenerations.
//
// NOTE this is a MODEL of a recording, not a recording. Parameters are matched to the
// ROI-1 reconnaissance (2026-06-23: recovered kernel peak +0.6 s, τ ≈ 2.7 s; measurement
// noise σ ≈ 0.0035 dF/F₀) so the figure is quantitatively plausible, but no real sample
// is reproduced and nothing here is evidence about the real cell.

import { makeGrid } from './timebase.js';
import { rasterize } from './rasterize.js';
import { buildKernel } from './kernels.js';
import { convolveOnGrid } from './convolve.js';
import { addAWGN, mulberry32 } from './noise.js';
import { AP_INDEPENDENT_SHAPES as EVENT_SHAPES } from './ap-independent.js';

/**
 * Morphologies for AP-independent calcium events — narrow (tall, brief, near-symmetric) and
 * slow (medium rise, minute-long tail), neither of which looks like the AP-linked transient.
 *
 * Defined in `ap-independent.js` and re-exported here. They used to live in this file, but
 * the same two shapes are now what the tabs' AP-independent slider injects: one definition
 * means the figure that ARGUES the phenomenon and the control that DEMONSTRATES it cannot
 * drift apart.
 */
export { EVENT_SHAPES };

/** Recording shape — matched to the real ROI-1 recording's length and frame rate. */
export const SIM = {
  rateHz: 10,
  durationS: 1080, // 18 min, as the real recording runs ~1067 s

  // AP→calcium kernel. τ values give a peak at ln(τd/τr)/(1/τr − 1/τd) ≈ 0.60 s with a
  // ~2.7 s decay, which is what deconvolution recovered from the real ROI 1.
  tauRise: 0.22,
  tauDecay: 2.7,
  /** Peak dF/F₀ contributed by ONE action potential. Clusters sum linearly from here. */
  apAmp: 0.019,

  // Spiking: clusters of 1–5 APs, tight enough that a cluster reads as one event.
  nClusters: 46,
  maxApsPerCluster: 5,
  apSpacingS: [0.15, 0.45],
  /** Cluster-onset jitter, in slot widths. >1 lets neighbours cross, so the train clumps. */
  jitterSlots: 1.7,

  // The violation: calcium with no spikes under it.
  //
  // These do NOT all share one shape, and that is the point. The real recording showed at
  // least two morphologies, neither of which matches the AP-linked transient — see
  // EVENT_SHAPES. A single shared shape made the figure read as one artifact stamped three
  // times; carrying the real variety is what makes "this is not the same process" legible
  // from the trace rather than only from the tick row.
  //
  // Amplitude and shape are authored; the TIMES are derived. An AP-independent event that
  // happens to land on a cluster reads as a coupled event with an implausible amplitude,
  // which defeats the whole demonstration, and hand-picked times get that wrong again the
  // moment the seed changes. So each is placed in one of the widest spike-free gaps (see
  // placeInQuietGaps). Listed in chronological order.
  independentEvents: [
    { amp: 0.14, shape: 'narrow' },
    { amp: 0.26, shape: 'slow' },
    { amp: 0.11, shape: 'narrow' },
  ],
  /**
   * Seconds of spike-free space required either side of an event's ONSET, so its rise is
   * unambiguously not spike-driven. The DECAY may overlap later spiking — the slow
   * morphology trails for a minute and did exactly that in the real recording.
   */
  independentClearS: 10,

  /** Measurement-noise floor from the ROI-1 reconnaissance (AWGN, σ in dF/F₀). */
  sigma: 0.0035,

  seed: 20260731,
};

/**
 * Build the simulated recording.
 *
 * @param {Partial<typeof SIM>} [overrides]
 * @returns {{
 *   times: Float64Array, calcium: Float64Array, clean: Float64Array,
 *   apLinked: Float64Array, apIndependent: Float64Array,
 *   spikes: number[], clusters: {atS:number, nAps:number}[],
 *   independentEvents: {atS:number, amp:number}[], dt: number, params: object
 * }}
 */
export function simulatePremise(overrides = {}) {
  const p = { ...SIM, ...overrides };
  const rand = mulberry32(p.seed);
  const grid = makeGrid({ sampleRate: p.rateHz, duration: p.durationS });

  // --- spikes: clusters of 1–5 APs -----------------------------------------
  // Cluster onsets are jittered slots rather than a Poisson draw. Poisson at this rate
  // produces runs and voids severe enough to read as an artifact of the draw; evenly
  // spaced slots read as a metronome, which is worse — no recording looks like that. The
  // jitter is deliberately wider than a slot (`jitterSlots` > 1), so neighbouring clusters
  // can cross and the train clumps and thins the way a real one does, while the overall
  // rate stays where it was put.
  const clusters = [];
  const spikes = [];
  const lead = 40; // leave a quiet head so the first event is not clipped
  const span = p.durationS - lead - 60;
  for (let c = 0; c < p.nClusters; c++) {
    const slot = lead + (span * c) / (p.nClusters - 1);
    const jitter = (rand() - 0.5) * (span / p.nClusters) * p.jitterSlots;
    const atS = Math.max(lead * 0.5, slot + jitter);
    const nAps = 1 + Math.floor(rand() * p.maxApsPerCluster); // 1…max inclusive
    clusters.push({ atS: round(atS, 2), nAps });
    let t = atS;
    for (let a = 0; a < nAps; a++) {
      spikes.push(round(t, 2));
      t += p.apSpacingS[0] + rand() * (p.apSpacingS[1] - p.apSpacingS[0]);
    }
  }
  spikes.sort((a, b) => a - b);

  // --- AP-linked calcium: one kernel per spike, summed by convolution -------
  // Unit-amplitude rasterization + a peak-apAmp kernel means a k-AP cluster sums to ~k×
  // apAmp automatically. No cluster-size special case exists, which is the point.
  const raster = rasterize(spikes, grid, { amplitudeMode: 'unit' });
  const apKernel = buildKernel('calcium', { tauRise: p.tauRise, tauDecay: p.tauDecay }, grid.dt, p.apAmp);
  const apLinked = convolveOnGrid(raster.samples, grid, apKernel).samples.slice(0, grid.n);

  // --- AP-independent calcium: per-event shape, no spikes ------------------
  // Each event carries its own kernel now, so these are stamped individually rather than
  // convolved as one impulse train. Stamping a causal kernel at an impulse IS that
  // convolution, without building a length-n input per event.
  const independentEvents = placeInQuietGaps(spikes, p);
  const apIndependent = new Float64Array(grid.n);
  for (const e of independentEvents) {
    const shape = EVENT_SHAPES[e.shape];
    if (!shape) throw new Error(`premise-sim: unknown event shape '${e.shape}'`);
    // zeroIndex differs by family — 0 for the causal calcium kernel, centred for the
    // gaussian — so the stamp offset below reads it rather than assuming.
    const k = buildKernel(shape.kernel, shape.params, grid.dt, e.amp);
    const i0 = Math.round((e.atS - grid.t0) / grid.dt);
    for (let j = 0; j < k.samples.length; j++) {
      const i = i0 + j - k.zeroIndex;
      if (i >= 0 && i < grid.n) apIndependent[i] += k.samples[j];
    }
  }

  // --- sum + measurement noise ---------------------------------------------
  const clean = new Float64Array(grid.n);
  for (let i = 0; i < grid.n; i++) clean[i] = apLinked[i] + apIndependent[i];
  const calcium = addAWGN(clean, p.sigma, mulberry32(p.seed + 1));

  return {
    times: grid.times,
    calcium,
    clean,
    apLinked,
    apIndependent,
    spikes,
    clusters,
    independentEvents,
    dt: grid.dt,
    params: p,
  };
}

/**
 * Put each AP-independent event in a spike-free gap, widest gaps first.
 *
 * The demonstration only works if these events sit somewhere with no action potential
 * under them — otherwise they read as an unusually large coupled event, which is the
 * opposite of the point. Deriving the times from the spike train keeps that true for any
 * seed, spike rate or cluster count, instead of until the next parameter change.
 *
 * @param {number[]} spikes ascending spike times (s)
 * @param {typeof SIM} p
 * @returns {{atS:number, amp:number}[]} chronological, amplitudes in the listed order
 */
export function placeInQuietGaps(spikes, p) {
  const n = p.independentEvents.length;
  const gaps = [];
  for (let i = 1; i < spikes.length; i++) {
    gaps.push({ from: spikes[i - 1], to: spikes[i], len: spikes[i] - spikes[i - 1] });
  }
  // Widest first, then keep the n widest and restore chronological order, so the amplitude
  // list reads left-to-right on the figure.
  const chosen = gaps
    .sort((a, b) => b.len - a.len)
    .slice(0, n)
    .sort((a, b) => a.from - b.from);

  if (chosen.length < n) {
    throw new Error(`premise-sim: only ${chosen.length} spike gaps for ${n} events`);
  }

  return chosen.map((g, i) => {
    // Sit far enough past the preceding AP that its transient has decayed, and leave a
    // clear run before the next one so the RISE is unambiguous. The tail is allowed to
    // run into later spiking — the slow morphology trails for most of a minute, and did
    // exactly that in the real recording.
    const earliest = g.from + 4 * p.tauDecay;
    const latest = g.to - p.independentClearS;
    const atS = latest > earliest ? (earliest + latest) / 2 : (g.from + g.to) / 2;
    return { atS: round(atS, 2), ...p.independentEvents[i] };
  });
}

function round(v, dp) {
  const f = 10 ** dp;
  return Math.round(v * f) / f;
}
